"use client";

import { useEffect, useMemo, useState } from "react";

type Track = { title: string; isrc: string; explicit: boolean };
type Contract = {
  contractDate: string; contractNumber: string; tariff: string; artistShare: number;
  releaseType: string; workTitle: string; pseudonym: string; genre: string; language: string; releaseDate: string;
  licensorName: string; passportSeriesNumber: string; passportIssuedBy: string; passportIssueDate: string;
  bankDetails: string; email: string; contact: string; musicAuthor: string; lyricsAuthor: string; noLyrics: boolean;
  tracks: Track[]; rightsConfirmed: boolean;
};
const initial: Contract = {
  contractDate: new Date().toISOString().slice(0, 10), contractNumber: "PFV-2026-____", tariff: "Премиум", artistShare: 90,
  releaseType: "Сингл", workTitle: "", pseudonym: "", genre: "", language: "Русский", releaseDate: "", licensorName: "",
  passportSeriesNumber: "", passportIssuedBy: "", passportIssueDate: "", bankDetails: "", email: "", contact: "",
  musicAuthor: "", lyricsAuthor: "", noLyrics: false, tracks: [{ title: "", isrc: "", explicit: false }], rightsConfirmed: false,
};
const sections = [{ id: "release", number: "01", label: "Релиз" }, { id: "licensor", number: "02", label: "Лицензиар" }, { id: "authors", number: "03", label: "Авторы" }, { id: "details", number: "04", label: "Реквизиты" }];
function formatDate(value: string) { if (!value) return "«___» __________ 2026 г."; return new Date(`${value}T00:00:00`).toLocaleDateString("ru-RU", { day: "2-digit", month: "long", year: "numeric" }); }
function display(value: string, fallback = "________________") { return value.trim() || fallback; }
function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
function SectionTitle({ number, title, caption }: { number: string; title: string; caption: string }) { return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2><p>{caption}</p></div></div>; }

function DocumentPreview({ data }: { data: Contract }) {
  const rows = data.tracks.filter((track) => track.title.trim());
  return <article className="paper" id="document-preview">
    <div className="paper-topline"><span>PFVMUSIC</span><span>Лицензионный договор</span></div>
    <header className="paper-header"><div className="paper-meta"><span>г. Тула</span><span>{formatDate(data.contractDate)}</span></div><h1>ЛИЦЕНЗИОННЫЙ ДОГОВОР PFVMUSIC</h1><div className="paper-contract-number">№ {display(data.contractNumber, "PFV-2026-____")}</div></header>
    <p className="indent">Гражданин Российской Федерации <b>{display(data.licensorName)}</b> (паспорт: {display(data.passportSeriesNumber)}, выдан {display(data.passportIssuedBy)}, дата выдачи {formatDate(data.passportIssueDate)}), именуемый в дальнейшем «Лицензиар», с одной стороны, и Индивидуальный предприниматель Орехов Данила Александрович (ОГРНИП 324710000080681), именуемый в дальнейшем «Лицензиат», с другой стороны, совместно именуемые «Стороны», заключили настоящий Лицензионный договор о нижеследующем.</p>
    <h3>1. Предмет договора</h3><p className="indent">1.1. Лицензиар предоставляет Лицензиату простую (неисключительную) лицензию на использование музыкального произведения «<b>{display(data.workTitle, "Название произведения")}</b>» под творческим псевдонимом «<b>{display(data.pseudonym, "Псевдоним")}</b>» ({data.releaseType.toLowerCase()}) на территории всего мира.</p><p className="indent">1.2. Разрешённые способы использования включают воспроизведение, распространение, доведение до всеобщего сведения, размещение на цифровых музыкальных сервисах и рекламное использование.</p>
    <h3>2. Объекты и авторы</h3><p className="indent">2.1. Жанр: <b>{display(data.genre)}</b>. Язык: <b>{display(data.language)}</b>. Планируемая дата релиза: <b>{formatDate(data.releaseDate)}</b>.</p>
    <table className="objects"><thead><tr><th>№</th><th>Название</th><th>ISRC</th><th>Explicit</th></tr></thead><tbody>{(rows.length ? rows : [{ title: "Название трека", isrc: "—", explicit: false }]).map((track, index) => <tr key={`${track.title}-${index}`}><td>{index + 1}</td><td>{display(track.title, "Название трека")}</td><td>{track.isrc || "—"}</td><td>{track.explicit ? "Да" : "Нет"}</td></tr>)}</tbody></table>
    <p className="indent">2.2. Автор музыки: <b>{display(data.musicAuthor)}</b>. Автор текста: <b>{data.noLyrics ? "текст отсутствует" : display(data.lyricsAuthor)}</b>.</p>
    <h3>3. Вознаграждение и отчётность</h3><p className="indent">3.1. За предоставление прав Лицензиар получает <b>{data.artistShare}%</b> дохода, фактически полученного Лицензиатом от использования Объектов, за вычетом документально подтверждённых комиссий площадок.</p><p className="indent">3.2. Выплаты производятся на реквизиты Лицензиара после достижения минимальной суммы выплаты и предоставления необходимых данных.</p>
    <h3>4. Гарантии сторон</h3><p className="indent">4.1. Лицензиар гарантирует, что обладает необходимыми правами на Объекты, а их использование по настоящему Договору не нарушает права третьих лиц. Лицензиар самостоятельно урегулирует требования соавторов и иных правообладателей.</p><p className="indent">4.2. Лицензиат вправе использовать имя и псевдоним Лицензиара в объёме, необходимом для размещения и продвижения релиза.</p>
    <h3>5. Срок действия и заключительные положения</h3><p className="indent">5.1. Договор вступает в силу с даты подписания и действует до его расторжения или прекращения прав на соответствующие Объекты. Изменения оформляются в письменной или электронной форме.</p><p className="indent">5.2. Во всём остальном Стороны руководствуются законодательством Российской Федерации. Неотъемлемой частью Договора является Приложение № 1 с перечнем Объектов.</p>
    <div className="signature-grid"><div><span>ЛИЦЕНЗИАР</span><strong>{display(data.licensorName)}</strong><i>________________ / подпись</i></div><div><span>ЛИЦЕНЗИАТ</span><strong>ИП Орехов Данила Александрович</strong><i>________________ / подпись</i></div></div><div className="paper-footer">Версия шаблона: license-v2.2-2026-07-30 · Сформировано в PFVFORM</div>
  </article>;
}

export default function Home() {
  const [data, setData] = useState<Contract>(() => { try { const saved = window.localStorage.getItem("pfv-contract-draft"); return saved ? { ...initial, ...JSON.parse(saved) } : initial; } catch { return initial; } }); const [active, setActive] = useState("release"); const [savedAt, setSavedAt] = useState(""); const [toast, setToast] = useState("");
  useEffect(() => { const timeout = window.setTimeout(() => { window.localStorage.setItem("pfv-contract-draft", JSON.stringify(data)); setSavedAt(new Date().toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" })); }, 350); return () => window.clearTimeout(timeout); }, [data]);
  const update = <K extends keyof Contract>(key: K, value: Contract[K]) => setData((current) => ({ ...current, [key]: value }));
  const completeness = useMemo(() => { const required = [data.workTitle, data.pseudonym, data.licensorName, data.passportSeriesNumber, data.email, data.musicAuthor]; return Math.round(required.filter(Boolean).length / required.length * 100); }, [data]);
  const jumpTo = (id: string) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  const exportDraft = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${data.contractNumber || "pfv-contract"}.json`; link.click(); URL.revokeObjectURL(url); showToast("Черновик сохранён в файл"); };
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">PFV</div><div><strong>PFVFORM</strong><span>Конструктор договоров</span></div></div><div className="top-actions"><span className="saved-state"><span className="status-dot" />{savedAt ? `Сохранено в ${savedAt}` : "Автосохранение"}</span><button className="ghost-button" onClick={exportDraft}>Экспорт черновика</button><button className="primary-button" onClick={() => window.print()}>Печать / PDF</button></div></header>
    <div className="workspace"><aside className="sidebar"><div className="sidebar-intro"><span className="eyebrow">ЛИЦЕНЗИОННЫЙ ДОГОВОР</span><h1>Заполните договор<br /><em>за 5 минут.</em></h1><p>Данные подставляются в документ автоматически — справа всегда актуальная версия.</p></div><div className="progress-card"><div className="progress-head"><span>Заполнено</span><b>{completeness}%</b></div><div className="progress-track"><span style={{ width: `${completeness}%` }} /></div><small>Черновик сохраняется на этом устройстве</small></div><nav className="steps-nav" aria-label="Разделы договора">{sections.map((section) => <button key={section.id} className={active === section.id ? "active" : ""} onClick={() => jumpTo(section.id)}><span>{section.number}</span>{section.label}<i>→</i></button>)}</nav><div className="tip-card"><span>✦</span><div><b>Совет</b><p>Подготовьте паспортные данные и банковские реквизиты — они понадобятся для выплаты.</p></div></div><div className="sidebar-foot">Шаблон PFVMUSIC<br /><span>license-v2.2 · 30.07.2026</span></div></aside>
      <section className="form-column"><div className="mobile-doc-actions"><button onClick={() => document.getElementById("document-preview")?.scrollIntoView({ behavior: "smooth" })}>Посмотреть договор ↓</button></div>
        <section className="form-section" id="release"><SectionTitle number="01" title="О релизе" caption="Основная информация о произведении и условиях лицензии" /><div className="form-grid two"><Field label="Название релиза" value={data.workTitle} onChange={(value) => update("workTitle", value)} placeholder="Например, Последний танец" /><Field label="Артист / псевдоним" value={data.pseudonym} onChange={(value) => update("pseudonym", value)} placeholder="Как указать на площадках" /><Field label="Жанр" value={data.genre} onChange={(value) => update("genre", value)} placeholder="Pop, hip-hop, electronic" /><label className="field"><span>Язык произведения</span><select value={data.language} onChange={(event) => update("language", event.target.value)}><option>Русский</option><option>Английский</option><option>Инструментальный</option><option>Другой</option></select></label><label className="field"><span>Тип релиза</span><select value={data.releaseType} onChange={(event) => update("releaseType", event.target.value)}><option>Сингл</option><option>EP</option><option>Альбом</option></select></label><Field label="Дата релиза" type="date" value={data.releaseDate} onChange={(value) => update("releaseDate", value)} /></div><div className="tariff-row"><div><span className="mini-label">Условия PFVMUSIC</span><strong>{data.tariff} · {data.artistShare}% артисту</strong></div><label className="share-control">Твоя доля<select value={data.artistShare} onChange={(event) => update("artistShare", Number(event.target.value))}><option value="70">70%</option><option value="90">90%</option><option value="100">100%</option></select></label></div><div className="tracks-block"><div className="subhead"><div><b>Треки релиза</b><span>Добавьте все композиции, входящие в договор</span></div><button className="text-button" onClick={() => update("tracks", [...data.tracks, { title: "", isrc: "", explicit: false }])}>+ Добавить трек</button></div>{data.tracks.map((track, index) => <div className="track-row" key={index}><span className="track-index">{String(index + 1).padStart(2, "0")}</span><input aria-label={`Название трека ${index + 1}`} placeholder="Название трека" value={track.title} onChange={(event) => update("tracks", data.tracks.map((item, i) => i === index ? { ...item, title: event.target.value } : item))} /><input aria-label={`ISRC трека ${index + 1}`} placeholder="ISRC (необязательно)" value={track.isrc} onChange={(event) => update("tracks", data.tracks.map((item, i) => i === index ? { ...item, isrc: event.target.value } : item))} /><label className="check small"><input type="checkbox" checked={track.explicit} onChange={(event) => update("tracks", data.tracks.map((item, i) => i === index ? { ...item, explicit: event.target.checked } : item))} /><span>18+</span></label>{data.tracks.length > 1 && <button className="remove-button" onClick={() => update("tracks", data.tracks.filter((_, i) => i !== index))}>×</button>}</div>)}</div></section>
        <section className="form-section" id="licensor"><SectionTitle number="02" title="Лицензиар" caption="Паспортные данные правообладателя — физического лица" /><div className="form-grid two"><Field label="ФИО полностью" value={data.licensorName} onChange={(value) => update("licensorName", value)} placeholder="Иванов Иван Иванович" /><Field label="Серия и номер паспорта" value={data.passportSeriesNumber} onChange={(value) => update("passportSeriesNumber", value)} placeholder="0000 000000" /><Field label="Кем выдан паспорт" value={data.passportIssuedBy} onChange={(value) => update("passportIssuedBy", value)} placeholder="Отделом МВД России..." /><Field label="Дата выдачи" type="date" value={data.passportIssueDate} onChange={(value) => update("passportIssueDate", value)} /></div><div className="privacy-note"><span>⌁</span><p>Эти данные нужны только для формирования договора и выплаты вознаграждения. Храните заполненный файл в безопасном месте.</p></div></section>
        <section className="form-section" id="authors"><SectionTitle number="03" title="Авторы и права" caption="Кто создавал музыку и текст произведения" /><div className="form-grid two"><Field label="Автор музыки / композитор" value={data.musicAuthor} onChange={(value) => update("musicAuthor", value)} placeholder="ФИО или псевдоним" /><Field label="Автор текста" value={data.lyricsAuthor} onChange={(value) => update("lyricsAuthor", value)} placeholder="ФИО или псевдоним" /></div><label className="check"><input type="checkbox" checked={data.noLyrics} onChange={(event) => update("noLyrics", event.target.checked)} /><span>В произведении нет текста (инструментал)</span></label><label className="check rights-check"><input type="checkbox" checked={data.rightsConfirmed} onChange={(event) => update("rightsConfirmed", event.target.checked)} /><span>Подтверждаю, что обладаю правами на произведение и получил(а) согласия соавторов</span></label></section>
        <section className="form-section" id="details"><SectionTitle number="04" title="Контакты и реквизиты" caption="Для связи и перечисления вознаграждения" /><div className="form-grid two"><Field label="Электронная почта" type="email" value={data.email} onChange={(value) => update("email", value)} placeholder="you@example.com" /><Field label="Телефон или Telegram" value={data.contact} onChange={(value) => update("contact", value)} placeholder="+7 900 000-00-00" /></div><label className="field full"><span>Банковские реквизиты</span><textarea value={data.bankDetails} onChange={(event) => update("bankDetails", event.target.value)} placeholder="Номер карты / счёта, БИК или ссылка на удобный способ выплаты" rows={3} /></label><div className="form-footer"><div><span className="secure-icon">✓</span><span>Перед отправкой проверьте все данные<br /><small>Исправить их можно в любой момент</small></span></div><button className="primary-button large" onClick={() => { showToast("Договор готов к проверке справа"); document.getElementById("document-preview")?.scrollIntoView({ behavior: "smooth" }); }}>Проверить договор <span>→</span></button></div></section>
      </section>
      <aside className="preview-column"><div className="preview-header"><div><span className="eyebrow">ЖИВОЙ ПРЕДПРОСМОТР</span><h2>Документ договора</h2></div><span className="preview-badge">A4 · {completeness}%</span></div><div className="preview-frame"><DocumentPreview data={data} /></div><div className="preview-note"><span>↗</span><p>Поля с пустыми значениями отмечены линиями. Перед подписанием внимательно проверьте документ.</p></div></aside>
    </div>{toast && <div className="toast">✓ {toast}</div>}
  </main>;
}
